function initFiles(data_path)
    global parameters

    % Create all necessary directiries (a directory for each subject, containg Results and TaskMaps)
    %--------------------------------------------------------------------------------------------------------------------------------------%
    % specify the directories to be used
    SUB_DIR = [data_path '/' 'sess' ...
        parameters.session '/' parameters.task '/']; % create a "SubNum" dir inside the "SubjectData" dir
    TASK_MAPS_DIR = [SUB_DIR 'TaskMaps/'];  % create a "TaskMaps" dir inside the "SubNum" dir
    RESULTS_DIR = [SUB_DIR 'Results/']; % create a "Results" dir inside the "SubNum" dir
    EYE_DIR = [SUB_DIR 'EyeData/']; % create a "EyeData" dir inside the "SubNum" dir

    createDirectories(parameters.subject,SUB_DIR,RESULTS_DIR,TASK_MAPS_DIR,EYE_DIR);
    parameters.subjectDIR = SUB_DIR;
    % Initialize the files to write in
    %--------------------------------------------------------------------------------------------------------------------------------------%
    %specify naming format for the data file
    date_time = datestr(now, 'mm_dd_yy_HH_MM_SS');
    
    %subNumStr = parameters.subject;
    %task = parameters.task;
    %coilLocStr = parameters.coilLocInd; 
    %sessionNumStr = parameters.session;
    taskMapFile = [TASK_MAPS_DIR parameters.currentStudy '_' ...
        parameters.currentStudyVersion '_sub' parameters.subject ...
        '_sess' parameters.session '_' parameters.task '_coilLoc'...
        num2str(parameters.coilLocInd, '%02d') '_' ...
        date_time '_taskMap.mat'];
    %edfFile = [parameters.subject parameters.session '.edf'];% can only be 4 characters long
    edfFile = [EYE_DIR parameters.subject '_' parameters.session '_' ...
        num2str(parameters.runNumber, '%02d') '_' ...
        num2str(parameters.runVersion, '%02d') '_' parameters.task '.edf'];
    datafile = [RESULTS_DIR parameters.currentStudy  '_' ...
        parameters.currentStudyVersion '_' parameters.subject ...
        '_' parameters.session '_' num2str(parameters.runNumber, '%02d')...
        '_' parameters.task '_' num2str(parameters.runVersion, '%02d') ...
        '_' date_time '.csv'];
    matfile = [RESULTS_DIR parameters.currentStudy '_' ...
        parameters.currentStudyVersion '_' parameters.subject ...
        '_' parameters.session '_' num2str(parameters.runNumber, '%02d')...
        '_' parameters.task '_' num2str(parameters.runVersion, '%02d') ...
        '_' date_time '.mat']; 
  
    parameters.taskMapFile = taskMapFile;
    parameters.edfFile = edfFile;

    parameters.datafile = datafile;
    parameters.matfile = matfile;
end